/* Full local adventure data extracted from the user's supplied Word document.
 * Keep this file local to the authorized project; image assets are in img/adventures/skyhorn/.
 */
const ADVENTURES = [
  {
    "id": "skyhorn-lighthouse",
    "title": "The Secrets of Skyhorn Lighthouse",
    "genre": "Coastal mystery · Exploration · Rescue",
    "level": "Use the level specified in the adventure text",
    "duration": "Full multi-scene adventure",
    "cover": "img/adventures/skyhorn/cover.jpg",
    "coverClass": "cover-sea",
    "summary": "Play through the complete supplied adventure text, from the harbor rumors and dockside confrontation to the lighthouse, flooded caverns, hostages, summoning room, aftermath, maps reference, and monster appendix.",
    "startScene": "harbor-rumors",
    "scenes": {
      "overview": {
        "id": "overview",
        "chapter": "Reference · Before Play",
        "title": "Adventure Overview",
        "text": [
          "THE SECRETS OF SKYHORN LIGHTHOUSE",
          "The Secrets of Skyhorn Lighthouse is a Dungeons & Dragons adventure designed for a group of four or 2ive players of 5th-level characters.",
          "This adventure is meant to be dropped into any Dungeons & Dragons setting with a nearby seaport or harbor town.",
          "BY KELSEY DIONNE",
          "SYNOPSIS",
          "At the beginning of the adventure, the party learns through one of the hooks that ships have stopped transiting the harbor for fear of “sea monsters.” They also learn nearby Skyhorn Lighthouse is in distress. The party is able to 2ind one captain, Sheila Coppertree, who is willing to risk going to the lighthouse.",
          "On the way to the lighthouse, a water elemental attacks the group. When the adventurers arrive at the lighthouse, they 2ind it under siege by eelfolk.",
          "The party learns of 2looded caves beneath the lighthouse either through exploration or from Lucien Skyhorn, the lighthouse keeper who is barricaded in the lantern room.",
          "Inside the caves, the group discovers the eelfolk are forcing captured sailors to use a Bowl of Commanding Water Elementals to summon water elementals and wreak havoc on the surrounding sea passage and harbor.",
          "BACKGROUND",
          "Lucien Skyhorn is sworn to protect the secret Bowl of Commanding Water Elementals hidden in the watery caves below his family’s ancestral lighthouse.",
          "A few days before the adventure begins, a raiding group of eelfolk entered the caves below the lighthouse via a hidden cove. There, they discovered the bowl. Since then, they've used it to capture a merchant ship that was transiting the harbor. The eelfolk learned (the hard way) that a summoned elemental sometimes turns against its summoner, so now they’re forcing the captured crew to do the summoning ritual.",
          "The eelfolk are trying to 2inish off Lucien, who is barricaded in the top room of the lighthouse. They plan to seize total control of the small island to continue using more water elementals to capture passing ships. They feel Lucien’s stubborn presence is a threat to their plans.",
          "A WORD TO THE GM",
          "This adventure is meant to be run at a glance with minimal preparation and a natural delivery. This required re-thinking the normal adventure presentation a bit. Here’s what you’ll 2ind included:",
          "Each encounter contained on one page.",
          "Bulleted lists. Bolded keywords.",
          "Hyperlinks to monsters and rules online for quick reference.",
          "Printable cards for each monster and PC so you can run encounters using a card stack. A short video walkthrough of this method can be found here.",
          "Short room and area descriptions. No paragraphs of droning 2lavor text — set the scene naturally and embellish as desired.",
          "Brie2ly explained non-encounter rooms. Again, embellish as desired!",
          "GM maps and player-safe digital maps for use with virtual tabletops.",
          "Printable cards for special treasure handout.",
          "A short video walkthrough of the adventure can be found here.",
          "PACING/TRANSITIONS",
          "A dramatic question is presented with most scenes. Once that question has been answered, the tension of the scene is resolved. That’s your cue to work toward the transition provided at the end the scene — even if that means summarizing the end of a clearly decided combat, or in the case of clever players, skipping combat altogether. Keep the game moving toward the next challenge!",
          "Room descriptions that are usually long blocks of literary read-aloud text have been left short and informational in this adventure.",
          "Many Game Masters prefer to paraphrase read-aloud text and set the scene based on what tone and level of detail his or her group 2inds engaging. Anything listed before the Development sections is safe to share however you prefer to do so."
        ],
        "choices": [
          {
            "label": "Begin the adventure",
            "target": "harbor-rumors"
          }
        ]
      },
      "harbor-rumors": {
        "id": "harbor-rumors",
        "chapter": "Chapter 1 · The Coast",
        "title": "Rumors In The Harbor",
        "text": [
          "The characters begin in any harbor or coastal town. The town should have access to housing, basic provisions, and a shipping dock.",
          "A story has been spreading about town that there’s a sea monster attacking ships near Skyhorn Lighthouse. Traf2ic in the harbor has come to a standstill amid the rumor.",
          "At any point during the PCs’ time in town, use some or all of the following hooks to introduce them to the adventure:",
          "APPEAL TO REWARD",
          "A very concerned merchant named Benji Frogwater (LG hal2ling noble) approaches the PCs, citing their reputation. He offers a reward of 200 gp each if the they’ll investigate a merchant ship of his, the Jade Lion, that was last seen in the waters near Skyhorn Lighthouse. He’s worried about the sea monster rumors and offers an additional 200 gp each if the party safely returns the crew (including his young son, Raf) and cargo.",
          "APPEAL TO HEROISM",
          "Captain Sheila Coppertree seeks out the group. She says she witnessed a massive wave grab a merchant ship, the Jade Lion, and drag it against the tide toward Skyhorn Lighthouse. A friend of hers, Captain Aryn Hest, was on board (alternatively, replace this with a mutual friend the PCs also know). She offers the party free transport to any harbor of their choice after the adventure if they go with her to help.",
          "APPEAL TO DISCOVERY",
          "A seagull lands on one of the characters. It opens its beak and says, “This is a message from Lucien Skyhorn, from the lighthouse. We’ve been attacked by creatures from the sea! Please, send help before it’s too late, I beg any who hears this…” Then the seagull squawks and 2laps away.",
          "TRANSITION",
          "The PCs go to the harbor to seek passage to or information about Skyhorn Lighthouse."
        ],
        "image": "img/adventures/skyhorn/source-assets/image1.jpeg",
        "imageAlt": "Artwork from the supplied Skyhorn Lighthouse adventure",
        "choices": [
          {
            "label": "Continue",
            "target": "scurvy-dogfight"
          }
        ]
      },
      "scurvy-dogfight": {
        "id": "scurvy-dogfight",
        "chapter": "Chapter 2 · Trouble at the Docks",
        "title": "Scurvy Dogfight",
        "text": [
          "THE DOCKS",
          "Skyhorn Lighthouse’s faint glimmer is visible on a small island a few miles out to sea.",
          "The docks are choked with ships. It’s quiet compared to the normal bustle of activity.",
          "DEVELOPMENT",
          "Sailors on the docks reiterate the rumor about the sea monster, some claiming falsely to have seen it (they fabricate a description). They refuse to take the PCs out to sea.",
          "If asked about who might take them to the lighthouse, sailors point the PCs in the direction of Sheila Coppertree’s sailing ship, the Annabel Lee (see Appendix A for maps).",
          "As the characters approach Sheila Coppertree’s ship, she swings down to the docks to greet them. Refer to the adventure hook Appeal to Heroism for what she knows.",
          "After a few moments of talking to Sheila, two pirates who lost a fair game of dice to her interrupt the conversation with demands that she pay up by turning over her ship. They've planned a surprise attack.",
          "DRAMATIC QUESTION",
          "Can the characters appease or defeat the pirate threat?",
          "TALK IT OUT",
          "Success if conUlict score reaches 0. Go to the combat section if it reaches 5.",
          "Gaspar and Neeno begin with a collective",
          "conUlict score of 3.",
          "A large bribe reduces their score by 1.",
          "A DC 15 Charisma (Persuasion) or Charisma (Deception) check reduces their score by 1. A failed check increases their score by 1.",
          "Using Charisma (Intimidation) increases their score by 1.",
          "Wisdom (Insight) DC 15 reveals one of the above details, or their current con2lict score.",
          "COMBAT",
          "Gaspar (G) and Neeno (N) shove characters into the water if given the chance.",
          "On round two, four of Neeno’s thugs (T) pop up on nearby ships and 2ire their crossbows.",
          "Enemies below one-third their hit points 2lee.",
          "TRANSITION",
          "The PCs collect what they need and strike out on the Annabel Lee toward the lighthouse."
        ],
        "choices": [
          {
            "label": "Continue",
            "target": "sea-monster-attacks"
          }
        ]
      },
      "sea-monster-attacks": {
        "id": "sea-monster-attacks",
        "chapter": "Chapter 3 · At Sea",
        "title": "Sea Monster Attacks",
        "text": [
          "APPROACHING THE DOCKS",
          "The Annabel Lee cuts through the ocean in a swift, bold path. It has a crew of 20 loyal sailors (they use the bandit statistics block). It reaches the bay in front of",
          "the lighthouse island after",
          "three hours.",
          "The lighthouse is situated on a steep, rocky island with a low stone wall at the top. The island is 100 feet in",
          "diameter.",
          "A staircase leads from a 40-foot wooden dock up a steep path to the lighthouse.",
          "The gate door at the top of the stairs 2laps",
          "open and closed like a broken gull wing.",
          "The Jade Lion",
          "merchant ship is not docked",
          "at the island — the docks are empty.",
          "DEVELOPMENT",
          "The Jade Lion is hidden in a narrow cove on the opposite side of the island that leads to Area 7 (see Appendix A: Maps).",
          "A water elemental in the bay attacks any incoming ships once they are within 80 feet of the docks.",
          "Characters whose passive Perception scores are 12 or higher notice a strange wave slicing toward the ship against the tide.",
          "The water elemental slams into the ship with a sickening crunch and boils out of the sea. Surprised PCs must pass a DC 15 Dexterity save or fall prone. Characters who noticed the elemental and brace themselves have advantage on the save.",
          "DRAMATIC QUESTION",
          "Can the characters defend the ship against the water elemental?",
          "COMBAT",
          "The water elemental is tall enough to attack creatures on the edge of the ship without leaving the water.",
          "It tries to use its Whelm action on the 2irst turn on two PCs at once.",
          "It is compelled by its summoner to 2ight until destroyed.",
          "Sheila steers for the safety of the docks. It takes three rounds to get there. She",
          "won’t move her ship again until she can inspect it.",
          "Treasure",
          "Upon defeat, the water elemental coughs up a pouch containing six",
          "Beads of Force.",
          "TRANSITION",
          "The group ascends the stairs to the lighthouse."
        ],
        "choices": [
          {
            "label": "Continue",
            "target": "under-siege"
          }
        ]
      },
      "under-siege": {
        "id": "under-siege",
        "chapter": "Chapter 4 · Lighthouse Under Siege",
        "title": "Under Siege",
        "text": [
          "APPROACHING THE LIGHTHOUSE",
          "The slippery stairs switchback 40 feet up to the 2lat, 100-foot diameter part of the island.",
          "The crumbling stone wall surrounding the top of the island is 10 feet high and can be scaled with a DC 10 Strength (Athletics) check. The gate door is broken open.",
          "The stone lighthouse is 60 feet tall, its blazing beam illuminating the sky.",
          "DEVELOPMENT",
          "The lighthouse door is barricaded and can be opened with a DC 18 Strength check. There is no guard posted outside.",
          "PCs can climb the damp lighthouse walls",
          "with a DC 20 Strength (Athletics) check.",
          "The lighthouse has two windows 40 feet off the ground that open into the stairwell between Areas 1 and 4. The glass can be shattered with a DC 12 Strength check or opened with a DC 15 Dexterity check. Area 4 has windows 60 feet up on two sides that can be opened with the same checks.",
          "Lucien Skyhorn is in Area 4. He’s de2iantly kept the lantern lit and burning bright for days. He can open a window from the inside.",
          "AREA 1: THE MAIN HALL",
          "Breaking down the door results in no surprise for either party.",
          "Smashed barrels and chairs litter the 2loor of the main hall. Tapestries with a nautilus shell symbol (the Skyhorn crest) are pulled from the walls and shredded.",
          "Six toothy eelfolk sit at the grand tables and jabber in Eelfolk. They are angrily discussing how to get into Area 4 and kill Lucien.",
          "DEVELOPMENT",
          "Characters can avoid detection each time they move or make noise within earshot of the eelfolk by making a group Dexterity (Stealth) check higher than the eelfolk hunters’ passive Perception 12 score. The eelfolk attack if they detect the PCs.",
          "DRAMATIC QUESTION",
          "Will the group avoid or defeat the eelfolk?",
          "COMBAT",
          "The four eelfolk (marked E) rush to attack the characters in melee. The two eelfolk hunters (marked H) 2lip the long tables over for half cover and throw javelins.",
          "Four more eelfolk and two eelfolk hunters join the combat from Area 2 on the second round of combat, excluding a possible surprise round.",
          "Treasure",
          "The eelfolk have 24 gp total, as well as an assortment of coral and shell trinkets.",
          "AREA 2: BARRACKS",
          "A room housing old bunk beds with frayed linens. An empty weapons rack sits against the eastern wall.",
          "AREA 3: STORE ROOM",
          "Moldy food and clawed-apart barrels are scattered around the room.",
          "DEVELOPMENT",
          "A hidden Uloor grate leads to Area 5. It can be located with a successful DC 20 Intelligence (Investigation) check.",
          "TRANSITION",
          "Characters move on to Area 4 or Area 5."
        ],
        "image": "img/adventures/skyhorn/source-assets/image9.jpeg",
        "imageAlt": "Artwork from the supplied Skyhorn Lighthouse adventure",
        "choices": [
          {
            "label": "Continue",
            "target": "light-in-tower"
          }
        ]
      },
      "light-in-tower": {
        "id": "light-in-tower",
        "chapter": "Chapter 5 · The Keeper",
        "title": "The Light In The Tower",
        "text": [
          "AREA 4: THE LANTERN ROOM",
          "The iron door at the top of the stairs is barricaded (DC 25 Strength check to open).",
          "DEVELOPMENT",
          "Lucien Skyhorn casts heat metal on the door if someone tries to batter it down.",
          "Lucien has been subsisting on conjured berries and water for the last few days and is desperate for help.",
          "The air inside the lantern room is heavy with the smell of burning oil. A massive lantern on a metal post streams a beam of light into the sky. Two glass windows offer high vantage points over the island and sea.",
          "A PLEA FOR HELP",
          "If the characters can convince Lucien through the door that they are allies, he will crack the door open and let them in.",
          "Lucien hopes the party will help him expel the eelfolk from the lighthouse.",
          "DRAMATIC QUESTION",
          "Will the characters help Lucien defeat the eelfolk and save the Bowl of Commanding Water Elementals?",
          "DISCUSSION WITH LUCIEN",
          "Lucien can share the following information:",
          "The eelfolk have discovered the Bowl of Commanding Water Elementals his family has kept secret in a cave below the lighthouse for six generations. The bowl is special; because it’s 2ixed in place, it can draw on the sea to summon elementals twice a day.",
          "Eelfolk are murderous raiders that lurk around shorelines and underwater caverns.",
          "The Skyhorn family uses the bowl to summon water elementals to help ailing ships reach harbor. There used to be many Skyhorns living on the island long ago.",
          "Lucien is the last of his family. He is sworn to protect the bowl and keep it from falling into evil hands.",
          "A summoned water elemental can break loose of its compulsion if the summoner’s will is not strong enough to control it. Lucien suspects several eelfolk have died this way and reasons they are now making their hostages summon the elementals instead.",
          "Lucien saw an elemental attack a merchant ship and tow it toward the back of the island where there’s a hidden cove (Area 7).",
          "The trap door to the caves is hidden below a heavy barrel in the corner of the supply room (Area 3) on the 2irst 2loor.",
          "The caves are 2looded in many areas.",
          "DEVELOPMENT",
          "If the PCs agree to save the Bowl of Commanding Water Elementals, Lucian gives each of them a Potion of Water Breathing.",
          "TRANSITION",
          "The PCs make their way to Area 1 or Area 5."
        ],
        "choices": [
          {
            "label": "Continue",
            "target": "caverns-below"
          }
        ]
      },
      "caverns-below": {
        "id": "caverns-below",
        "chapter": "Chapter 6 · The Flooded Caves",
        "title": "The Caverns Below",
        "text": [
          "AREA 5: SOMETHING IN THE DEEP",
          "A rusty ladder leads 10 feet down from the trap door in Area 3 into the briny water.",
          "The rise and crash of the tides echoes in these glimmering caves.",
          "The water is 50 feet deep. The cavern ceiling reaches 40 feet above the water.",
          "DEVELOPMENT",
          "Three hunter sharks lurk in the areas marked S on the map and will investigate sounds in",
          "the water. The eelfolk have been feeding them human",
          "hostages killed by elementals. The sharks attack",
          "once they are within 30 feet of anything in the water.",
          "The eelfolk have stacked four chests of loot from the merchant ship on the cave 2loor at the areas marked T. Characters carrying the heavy chests move at half speed.",
          "DRAMATIC QUESTION",
          "Can the PCs avoid or defeat the sharks?",
          "COMBAT",
          "The hunter sharks focus on characters who are already wounded in order to use their Blood Frenzy trait. They 2lee to the ocean out Area 7 if reduced below 15 hit points",
          "each.",
          "Treasure",
          "The chests contain 400 gp worth of 2ine goods: bottled perfumes, silverware, statues, jewelry, and other trinkets. A worn, black-hilted dagger is actually a Dagger of Venom.",
          "AREA 6: THE DOCK",
          "A small sandbar rises out of the water. Two rowboats are tied up at a rickety wooden dock anchored at the sandbar.",
          "The crumbling, 20 foot-high wall of an ancient, sunken tower juts from the cave wall. It can be climbed with a successful DC 13 Strength (Athletics) check.",
          "TRANSITION",
          "The characters continue onto the next part of the caves. The sharks may remain a threat if they haven’t been dispatched."
        ],
        "image": "img/adventures/skyhorn/source-assets/image20.png",
        "imageAlt": "Artwork from the supplied Skyhorn Lighthouse adventure",
        "choices": [
          {
            "label": "Continue",
            "target": "wounded-lion"
          }
        ]
      },
      "wounded-lion": {
        "id": "wounded-lion",
        "chapter": "Chapter 7 · The Wreck",
        "title": "Wounded Lion",
        "text": [
          "AREA 7: THE MERCHANT SHIP",
          "The open sea can be seen beyond the mouth of this cove.",
          "The merchant’s sailing ship, the Jade Lion, is anchored at the opening of the cove. It lists in the water just out of reach of the jagged walls. One of its masts is snapped and missing.",
          "There are two remaining rowboats tied to the ship that are identical to the ones in Area 5.",
          "DEVELOPMENT",
          "The tide is very strong in the 10-foot wide channel leading to the ship and requires a DC 13 Strength (Athletics) check to swim. Characters who fail by 5 or more take 7 (2d6) bludgeoning damage as they’re slammed into the walls.",
          "With the snapped mast, the Jade Lion can sail at half speed with a DC 15 Wisdom (Survival) check when crewed by at least 10 sailors.",
          "The ship has been heavily looted. Crates of exotic fruits and bolts of 2ine cloth have been strewn about and destroyed. No crew are on board.",
          "Stowaway: Raf Frogwater, the merchant Benji Frogwater’s eight-year-old son and apprentice. Raf hides in a secret cabinet in the captain’s quarters and can be found with a successful DC 14 Intelligence (Investigation) check. He approaches the PCs upon hearing them speak a language he understands. He’s damp, scared, and hungry.",
          "DISCUSSION WITH RAF",
          "Raf can share the following information:",
          "A gigantic wave of water grabbed onto the ship and dragged it into the cove.",
          "The “eel-men” ransacked the ship and took the crew inside the cave, including Captain Aryn Hest, Sheila Coppertree’s friend.",
          "One of the “eel-men” was bigger and angrier than the others. He bossed them around.",
          "There were about 10 “eel-men,” but it was hard to count from his hiding spot.",
          "One or two big waves have passed by each day. They make the ship bob and spin like a toy.",
          "Raf sometimes hears human screams and terrible crashes echoing in the caves.",
          "He hasn’t been in the caves and doesn’t know their layout.",
          "Treasure",
          "The eelfolk looters missed a silver candle holder worth 25 gp, as well as a gold ring in a mahogany lockbox worth 50 gp.",
          "TRANSITION",
          "The group returns to the caves and continue exploring."
        ],
        "choices": [
          {
            "label": "Continue",
            "target": "hostages"
          }
        ]
      },
      "hostages": {
        "id": "hostages",
        "chapter": "Chapter 8 · The Hostages",
        "title": "Hostages",
        "text": [
          "AREA 8: THE CREW",
          "The doors leading to and from this room are unlocked.",
          "A large, faded nautilus shell (the Skyhorn family symbol) is carved into the 2loor tiles.",
          "Twelve human commoners are lashed together in groups of four (marked P on the map). They are the Jade Lion’s surviving crew. They are beaten, starved, and terrorized.",
          "Aryn Hest, the captain of the Jade Lion, is among the living prisoners. He has jagged electrical burns on his hands and arms.",
          "Two eelfolk (marked E) sit near the door playing a violent game involving coral caltrops. They bolt for the door to Area 9 when they spot the characters.",
          "DRAMATIC QUESTION",
          "Can the party stop the eelfolk from alerting their companions in Area 9?",
          "COMBAT",
          "Both eelfolk attempt to open the door to Area 9 and alert the other eelfolk.",
          "Aryn Hest tries to trip any eelfolk who run near him. He doesn’t have any equipment.",
          "Aryn warns the characters that the eelfolk are forcing one of his crew to summon another water elemental in the next room.",
          "THE EELFOLK ALERT THE OTHERS",
          "All of the eelfolk take cover behind the stalactites or rubble and ready actions to attack when the PCs enter the room.",
          "If the characters wait any longer than two minutes, the sailor in Area 9 is forced to summon a water elemental. The elemental crashes into Area 8 to attack the PCs.",
          "There’s a 30% chance each round the sailor will lose his concentration if he summons a water elemental. If that happens, the elemental becomes hostile toward him.",
          "THE EELFOLK DON’T ALERT THE OTHERS",
          "Aryn urges the PCs to stop the summoning ritual happening in Area 9.",
          "The eelfolk in Area 9 are too engrossed with the summoning ritual to hear the combat in Area 8 (barring an explosion or similar).",
          "The eelfolk are in the positions marked on the map when the characters enter",
          "Area 9.",
          "The PCs may be able to set up a surprise round in Area 9 if",
          "they beat the eelfolk scourge’s passive Perception score of 13.",
          "AREA 8A: PLUNDER",
          "The eelfolk have stacked chests and barrels of plunder from the Jade Lion in here.",
          "They contain 5,000 gp worth of trade goods.",
          "The door to Area 8 is unlocked.",
          "TRANSITION",
          "The characters have only a moment to prepare before the action in Area 9 begins."
        ],
        "choices": [
          {
            "label": "Continue",
            "target": "summoning-room"
          }
        ]
      },
      "summoning-room": {
        "id": "summoning-room",
        "chapter": "Chapter 9 · The Ritual",
        "title": "Summoning Room",
        "text": [
          "AREA 9: STALAGMITE CAVE",
          "Clusters of stalagmites bunch together in this damp cavern.",
          "A crumbling, round chamber sits along east the wall.",
          "A shimmering, water-2illed bowl is set into cracked, alabaster tiles at the back of the cavern. It’s the Bowl of Commanding Water Elementals.",
          "An eelfolk scourge screams (in Eelfolk) over a terri2ied sailor kneeling in front of the bowl.",
          "Other kinds of eelfolk are scattered around the room watching the ritual.",
          "DRAMATIC QUESTION",
          "Can the characters stop the summoning ritual in time and defeat the eelfolk?",
          "COMBAT",
          "The eelfolk scourge (marked ES) moves into melee against a weak-looking PC.",
          "The eelfolk (marked E) gang up on stronger characters and try to surround them.",
          "The eelfolk hunters (marked H) hurl javelins from cover within the circular chamber. They throw javelins for three rounds and then and join the melee.",
          "The broken tower crenellations and the stalactites provide half cover.",
          "The browbeaten sailor (marked S) named Grigor (CN bandit, no weapons) will continue to single-mindedly summon the water elemental until halted. He fears torture if he stops. He completes the ritual on the end of his 4th turn of unbroken concentration.",
          "TRANSITION",
          "The group moves on to the Aftermath section."
        ],
        "choices": [
          {
            "label": "Continue",
            "target": "aftermath"
          }
        ]
      },
      "aftermath": {
        "id": "aftermath",
        "chapter": "Chapter 10 · Aftermath",
        "title": "Aftermath",
        "text": [
          "THE BOWL OF COMMANDING WATER ELEMENTALS",
          "Lucien would not take kindly to characters trying to take the bowl. He does not award them anything but a terse “thank-you and goodbye” if they attempt to do so.",
          "The bowl loses all magical properties if pried out of the ground.",
          "As long as the PCs don’t attempt to take the bowl, Lucien gives each one a Mariner’s Coin in thanks for their help. The coin is a hammered copper piece stamped with a shining",
          "lighthouse. When presented to a non-hostile sailor, it",
          "grants advantage on one Charisma check to in2luence him or her.",
          "SAILING THE JADE LION",
          "If still alive, Aryn Hest is grateful to the characters and helps get the cargo and exhausted crew back onto the Jade Lion using the ship’s spare rowboats. He’s able to sail the Jade Lion back to port for repairs.",
          "RETURNING HOME",
          "The Annabel Lee suffered minor damage from the elemental but can sail normally.",
          "Benji Frogwater awards the characters 200 gp each if they return Raf to him. He awards an additional 200 gp each if the characters return the surviving crew and chests of goods.",
          "Benji sends a detachment of four soldiers and one captain to repair and guard the lighthouse henceforth.",
          "Sheila Coppertree will sail the characters to any port of their choice, as promised.",
          "FUTURE ADVENTURE HOOKS",
          "Captain Sheila may be impressed by the PCs’ valor and offer them a new mission.",
          "Adventure may ensue on the open sea if Sheila transports the group somewhere.",
          "Lucien may seek the PCs out again when a strange sailor visits the lighthouse.",
          "The characters may wish to pursue and root out a nearby eelfolk clan, which is rumored to be lead by a recently ascended eelfolk stormcaller…"
        ],
        "choices": [
          {
            "label": "Read Appendix A: Maps and Artwork",
            "target": "maps-reference"
          },
          {
            "label": "Open Appendix B: New Monster Statistics",
            "target": "new-monsters"
          },
          {
            "label": "Return to the adventure library",
            "target": "__LIBRARY__"
          }
        ]
      },
      "maps-reference": {
        "id": "maps-reference",
        "chapter": "Reference · Maps",
        "title": "APPENDIX A: MAPS",
        "text": [
          "THE DOCKS",
          "THE ANNABEL LEE",
          "SKYHORN LIGHTHOUSE",
          "SKYHORN LIGHTHOUSE CAVES",
          "Local artwork assets extracted from the provided Word document are stored in img/adventures/skyhorn/source-assets/. These include maps and illustrations; open the files locally to identify and place them as needed.",
          "Artwork file: image1.jpeg (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image10.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image11.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image12.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image13.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image14.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image15.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image16.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image17.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image18.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image19.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image2.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image20.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image21.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image22.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image23.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image24.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image25.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image26.jpeg (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image27.jpeg (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image28.jpeg (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image29.jpeg (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image3.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image30.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image31.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image32.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image4.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image5.jpeg (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image6.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image7.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image8.png (located in img/adventures/skyhorn/source-assets/)",
          "Artwork file: image9.jpeg (located in img/adventures/skyhorn/source-assets/)"
        ],
        "choices": [
          {
            "label": "Return to the adventure library",
            "target": "__LIBRARY__"
          },
          {
            "label": "Return to the aftermath",
            "target": "aftermath"
          }
        ]
      },
      "new-monsters": {
        "id": "new-monsters",
        "chapter": "Reference · Creature Statistics",
        "title": "APPENDIX B: NEW MONSTERS",
        "text": [
          "Eelfolk",
          "Eelfolk are a piscine race with rubbery skin and patterned coloration meant to provide camou2lage amid shifting underwater light.",
          "They slink and hunt through caves and shoals, carving out territory in bursts of aggressive expansion. Eelfolk often lair along shorelines and submerged caverns, never too far from the surface where they must occasionally gulp great mouthfuls of air.",
          "Ambushers. Eelfolk keep to the fringes of the sea and ambush any who encroach upon their territory. While hunting, they prefer to lie in wait for prey to draw close before lunging out to attack. Two pouches behind their necks generate an electrical charge they use to sense their quarry, even in the murkiest depths.",
          "Storm Worshippers. Eelfolk worship the squalls of the sea as though they were gods, viewing all storms as divinely inspired. Sailors at sea have reported seeing dozens of eelfolk",
          "cavorting through the water during tempests.",
          "Growing Pains. Eelfolk grow larger and more powerful with age, shifting from stealthy hunters to vicious brutes. Fully matured eelfolk",
          "grow extra electrical pouches that cover their bodies in crackling energy. These scourges are more cunning and aggressive than their younger brethren. They lead surprise raids along shoreline settlements in",
          "order to satiate their ever-growing hunger for violence and food.",
          "Storm’s Fury. During raging ocean storms, the strongest and most cunning eelfolk 2ight with each other to throw themselves in the path of a lightning strike. Rarely, one lucky creature will be enveloped in a great blast of energy. The lighting burns the eelfolk’s bulky body away, replacing it with a gaunt form housing magni2icent power. These eelfolk stormcallers gain the ability to channel the tempest’s might, summoning lightning bolts and gales of wind to pummel their foes.",
          "EELFOLK",
          "Medium humanoid (eelfolk), chaotic evil",
          "Armor Class 15 (hide armor, shield)",
          "Hit Points 19 (3d8 + 6)",
          "Speed 30 ft., swim 40 ft.",
          "STR\tDEX\tCON\tINT\tWIS\tCHA",
          "10 (+0)  13 (+1)  14 (+2)\t6 (-2)\t10 (+0)\t7 (-2)",
          "Skills Stealth +3",
          "Damage Immunities lightning",
          "Senses blindsight 60 ft., passive Perception 10",
          "Languages Eelfolk",
          "Challenge 1/2 (100 XP)",
          "Death Burst. When the eelfolk dies, it explodes in a burst of pent-up electricity. Each creature within 10 feet of it must make a DC 12 Dexterity saving throw, taking 7 (2d6) lightning damage on a failed save, or half as much on a successful one.",
          "Hold Breath. The eelfolk can hold its breath for 1 hour.",
          "Lunge. If the eelfolk moves at least 20 feet straight toward a target and then hits it with a long knife attack on the same turn, the target takes an extra 7 (2d6) piercing damage.",
          "Actions",
          "Long Knife. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) slashing damage.",
          "EELFOLK HUNTER",
          "Medium humanoid (eelfolk), chaotic evil",
          "Armor Class 13 (hide armor)",
          "Hit Points 39 (6d8 + 12)",
          "Speed 30 ft., swim 40 ft.",
          "EELFOLK SCOURGE",
          "Large humanoid (eelfolk), chaotic evil",
          "Armor Class 13 (hide armor)",
          "Hit Points 85 (10d10 + 30)",
          "Speed 30 ft., swim 40 ft.",
          "STR\tDEX\tCON\tINT\tWIS\tCHA",
          "14 (+2)  13 (+1)  14 (+2)\t6 (-2)\t10 (+0)\t7 (-2)",
          "STR\tDEX\tCON\tINT\tWIS\tCHA",
          "18 (+4)  13 (+1)  16 (+3)\t7 (-2)\t13 (+1)\t9 (-1)",
          "Skills Perception +2, Stealth +5",
          "Damage Immunities lightning",
          "Senses blindsight 60 ft., passive Perception 12",
          "Languages Eelfolk",
          "Challenge 1 (200 XP)",
          "Ambusher. The hunter has advantage on attack rolls against any creature it has surprised.",
          "Death Burst. When the eelfolk dies, it explodes in a burst of pent-up electricity. Each creature within 10 feet of it must make a DC 12 Dexterity saving throw, taking 7 (2d6) lightning damage on a failed save, or half as much on a successful one.",
          "Hold Breath. The eelfolk can hold its breath for 1 hour.",
          "Lunge. If the eelfolk moves at least 20 feet straight toward a target and then hits it with a spear attack on the same turn, the target takes an extra 7 (2d6) piercing damage.",
          "Actions",
          "Multiattack. The hunter makes two spear attacks.",
          "Spear. Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 6 (1d8 + 2) piercing damage (two-handed melee attack) or 5 (1d6 + 2) piercing damage (ranged attack).",
          "Skills Perception +3, Stealth +5",
          "Damage Immunities lightning",
          "Senses blindsight 60 ft., passive Perception 13",
          "Languages Eelfolk",
          "Challenge 4 (1,100 XP)",
          "Death Burst. When the eelfolk dies, it explodes in a burst of pent-up electricity. Each creature within 10 feet of it must make a DC 13 Dexterity saving throw, taking 7 (2d6) lightning damage on a failed save, or half as much on a successful one.",
          "ElectriBied Body. A creature that touches the scourge or hits it with a melee attack while within 5 feet of it takes 5 (1d10) lightning damage.",
          "Hold Breath. The eelfolk can hold its breath for 1 hour.",
          "Lunge. If the eelfolk moves at least 20 feet straight toward a target and then hits it with a claw or bite attack on the same turn, the target takes an extra 7 (2d6) piercing damage.",
          "Actions",
          "Multiattack. The scourge makes three melee attacks: one with its bite, two with its claws.",
          "Bite. Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 9 (2d4 + 4) piercing damage.",
          "Claws. Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.",
          "EELFOLK STORMCALLER",
          "Medium humanoid (eelfolk), chaotic evil",
          "Armor Class 15 (studded leather armor)",
          "Hit Points 117 (18d8 + 36)",
          "Speed 30 ft., swim 40 ft.",
          "STR\tDEX\tCON\tINT\tWIS\tCHA",
          "11 (+0)  16 (+3)  14 (+2)\t8 (-1)\t14 (+2)  18 (+4)",
          "Skills Intimidation +7, Perception +5, Stealth +9",
          "Damage Immunities lightning",
          "Senses blindsight 60 ft., passive Perception 15",
          "Languages Eelfolk",
          "Challenge 6 (2,300 XP)",
          "Death Burst. When the eelfolk dies, it explodes in a burst of pent-up electricity. Each creature within 10 feet of it must make a DC 13 Dexterity saving throw, taking 7 (2d6) lightning damage on a failed save, or half as much on a successful one.",
          "Hold Breath. The eelfolk can hold its breath for 1 hour.",
          "Innate Spellcasting. The stormcaller’s innate spellcasting ability is Charisma (spell save DC 15). It can innately cast the following spells, requiring no material components:",
          "At will: detect magic, thunderwave",
          "2/day each: call lightning, fog cloud, lightning bolt",
          "Actions",
          "Multiattack. The stormcaller makes two claw attacks.",
          "Claws. Melee Weapon Attack: +6 to hit, reach 5ft., one target. Hit: 6 (1d6 + 3) slashing damage plus 7 (2d6) lightning damage.",
          "Reactions",
          "Lighting ReBlexes. The stormcaller adds 3 to its AC against one melee attack that would hit it. To do so, the stormcaller must see the attacker.",
          "THE ARCANE LIBRARY",
          "If you join The Arcane Library's newsletter, you’ll get a FREE copy of Temple of the Basilisk Cult, a 1st-level adventure set in the jungle!",
          "Acknowledgements",
          "Special thanks to John from www.5thsrd.org for permission to link to his site. Very many thanks to The Angry GM for wisdom, especially about pacing and structure. Finally, my most heartfelt gratitude to Jessee Egan for phenomenal art direction and design.",
          "Credits",
          "Logos, trade dress, art direction: Jessee Egan / jesseeegan.com Cartography: OneDayGM / 2iverr.com",
          "Cover: Andrey Yurlov / shutterstock.com",
          "Additional cover art: Stephane Bidouze / shutterstock.com Fantasy Grounds module: Gwydion / www.twitch.tv/gwydione",
          "Compass, Pirate Fight, Barrel, Shark, Pirate Ring, Treasure Chest, Pirate, Coins: Publisher’s Choice Quality Stock Art © Rick Hershey / Fat Goblin Games",
          "Water Elemental: Gary Dupuis / Purple Duck Games",
          "© 2017 The Arcane Library, LLC. All rights reserved.",
          "Notice of Open Game Content: This product contains Open Game Content, as de2ined in the Open Game License Version 1.0a, below. Open Game Content may only be Used under and in terms of the Open Game License version 1.0a. No portion of this work other than previously designated Open Game Content may be reproduced in any form without written permission.",
          "Designation of Open Game Content: Subject to the Product Identity Designation herein, the following material is designated as Open Game Content. (1) all monster statistics, descriptions of special abilities, and sentences including game mechanics such as die rolls, probabilities, and/ or other material required to be Open Game Content as part of the game rules, or previously released as Open Game Content, (2) all portions of spell descriptions that include rules-speci2ic de2initions of the effect of the spells, and all material previously released as Open Game Content, (3) all other descriptions of game-rule effects specifying die rolls or other mechanic features of the game, whether in traps, magic items, hazards, or anywhere else in the text, (4) all previously released Open Game Content, material required to be Open Game Content under the terms of the Open Game License, and public domain material anywhere in the text.",
          "Product Identity Designation: This Product Identity Designation includes, but is not limited to, the following items that are hereby identi2ied as Product Identity, as de2ined in the Open Game License version 1.0a, Section 1(e): All trademarks, registered trademarks, proper names (characters, artifacts, place names, new deities, monsters, organizations, etc.), dialogue, plots, story elements, locations, characters, artwork, sidebars, logos, and trade dress. These items are not Open Game Content. Elements that have previously been designated as Open Game Content are not included in this declaration.",
          "OPEN GAME LICENSE Version 1.0a",
          "The following text is the property of Wizards of the Coast, Inc. and is Copyright 2000 Wizards of the Coast, Inc (\"Wizards\"). All Rights Reserved.",
          "DeUinitions: (a)\"Contributors\" means the copyright and/or trademark owners who have contributed Open Game Content; (b)\"Derivative Material\" means copyrighted material including derivative works and translations (including into other computer languages), potation, modi2ication, correction, addition, extension, upgrade, improvement, compilation, abridgment or other form in which an existing work may be recast, transformed or adapted; (c) \"Distribute\" means to reproduce, license, rent, lease, sell, broadcast, publicly display, transmit or otherwise distribute; (d)\"Open Game Content\" means the game mechanic and includes the methods, procedures, processes and routines to the extent such content does not embody the Product Identity and is an enhancement over the prior art and any additional content clearly identi2ied as Open Game Content by the Contributor, and means any work covered by this License, including translations and derivative works under copyright law, but speci2ically excludes Product Identity. (e) \"Product Identity\" means product and product line names, logos and identifying marks including trade dress; artifacts; creatures characters; stories, storylines, plots, thematic elements, dialogue, incidents, language, artwork, symbols, designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual or audio representations; names and descriptions of characters, spells, enchantments, personalities, teams, personas, likenesses and special abilities; places, locations, environments, creatures, equipment, magical or supernatural abilities or effects, logos, symbols, or graphic designs; and any other trademark or registered trademark clearly identi2ied as Product identity by the owner of the Product Identity, and which speci2ically excludes the Open Game Content; (f) \"Trademark\" means the logos, names, mark, sign, motto, designs that are used by a Contributor to identify itself or its products or the associated products contributed to the Open Game License by the Contributor (g) \"Use\", \"Used\" or \"Using\" means to use, Distribute, copy, edit, format, modify, translate and otherwise create Derivative Material of Open Game Content. (h) \"You\" or \"Your\" means the licensee in terms of this agreement.",
          "The License: This License applies to any Open Game Content that contains a notice indicating that the Open Game Content may only be Used under and in terms of this License. You must af2ix such a notice to any Open Game Content that you Use. No terms may be added to or subtracted from this License except as described by the License itself. No other terms or conditions may be applied to any Open Game Content distributed using this License.",
          "Offer and Acceptance: By Using the Open Game Content You indicate Your acceptance of the terms of this License.",
          "Grant and Consideration: In consideration for agreeing to use this License, the Contributors grant You a perpetual, worldwide, royalty free, non exclusive license with the exact terms of this License to Use, the Open Game Content.",
          "Representation of Authority to Contribute: If You are contributing original material as Open Game Content, You represent that Your Contributions are Your original creation and/or You have suf2icient rights to grant the rights conveyed by this License.",
          "Notice of License Copyright: You must update the COPYRIGHT NOTICE portion of this License to include the exact text of the COPYRIGHT NOTICE of any Open Game Content You are copying, modifying or distributing, and You must add the title, the copyright date, and the copyright holder's name to the COPYRIGHT NOTICE of any original Open Game Content you Distribute.",
          "Use of Product Identity: You agree not to Use any Product Identity, including as an indication as to compatibility, except as expressly licensed in another, independent Agreement with the owner of each element of that Product Identity. You agree not to indicate compatibility or co adaptability with any Trademark or Registered Trademark in conjunction with a work containing Open Game Content except as expressly licensed in another, independent Agreement with the owner of such Trademark or Registered Trademark. The use of any Product Identity in Open Game Content does not constitute a challenge to the ownership of that Product Identity. The owner of any Product Identity used in Open Game Content shall retain all rights, title and interest in and to that Product Identity.",
          "IdentiUication: If you distribute Open Game Content You must clearly indicate which portions of the work that you are distributing are Open Game Content.",
          "Updating the License: Wizards or its designated Agents may publish updated versions of this License. You may use any authorized version of this License to copy, modify and distribute any Open Game Content originally distributed under any version of this License.",
          "Copy of this License: You MUST include a copy of this License with every copy of the Open Game Content You Distribute.",
          "Use of Contributor Credits: You may not market or advertise the Open Game Content using the name of any Contributor unless You have written permission from the Contributor to do so.",
          "Inability to Comply: If it is impossible for You to comply with any of the terms of this License with respect to some or all of the Open Game Content due to statute, judicial order, or governmental regulation then You may not Use any Open Game Material so affected.",
          "Termination: This License will terminate automatically if You fail to comply with all terms herein and fail to cure such breach within 30 days of becoming aware of the breach. All sublicenses shall survive the termination of this License.",
          "Reformation: If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable.",
          "COPYRIGHT NOTICE",
          "Open Game License v 1.0a Copyright 2000, Wizards of the Coast, LLC. System Reference Document 5.1 Copyright 2016, Wizards of the Coast, Inc.; Authors Mike Mearls, Jeremy Crawford, Chris Perkins, Rodney Thompson, Peter Lee, James Wyatt, Robert J. Schwalb, Bruce R. Cordell, Chris Sims, and Steve Townshend, based on original material by E. Gary Gygax and Dave Arneson.",
          "The Secrets of Skyhorn Lighthouse © 2017 The Arcane Library, LLC. END LICENSE",
          "Embedded source asset: image1.jpeg — 119,278 bytes.",
          "Embedded source asset: image10.png — 17,951 bytes.",
          "Embedded source asset: image11.png — 465,241 bytes.",
          "Embedded source asset: image12.png — 3,487 bytes.",
          "Embedded source asset: image13.png — 294,416 bytes.",
          "Embedded source asset: image14.png — 12,417 bytes.",
          "Embedded source asset: image15.png — 495,189 bytes.",
          "Embedded source asset: image16.png — 6,054 bytes.",
          "Embedded source asset: image17.png — 271,161 bytes.",
          "Embedded source asset: image18.png — 446,864 bytes.",
          "Embedded source asset: image19.png — 11,080 bytes.",
          "Embedded source asset: image2.png — 5,174 bytes.",
          "Embedded source asset: image20.png — 1,185,746 bytes.",
          "Embedded source asset: image21.png — 3,167 bytes.",
          "Embedded source asset: image22.png — 267,334 bytes.",
          "Embedded source asset: image23.png — 9,584 bytes.",
          "Embedded source asset: image24.png — 264,814 bytes.",
          "Embedded source asset: image25.png — 550,160 bytes.",
          "Embedded source asset: image26.jpeg — 319,903 bytes.",
          "Embedded source asset: image27.jpeg — 113,117 bytes.",
          "Embedded source asset: image28.jpeg — 121,289 bytes.",
          "Embedded source asset: image29.jpeg — 299,139 bytes.",
          "Embedded source asset: image3.png — 44,739 bytes.",
          "Embedded source asset: image30.png — 344 bytes.",
          "Embedded source asset: image31.png — 5,274 bytes.",
          "Embedded source asset: image32.png — 177,472 bytes.",
          "Embedded source asset: image4.png — 160,227 bytes.",
          "Embedded source asset: image5.jpeg — 190,334 bytes.",
          "Embedded source asset: image6.png — 7,278 bytes.",
          "Embedded source asset: image7.png — 390,562 bytes.",
          "Embedded source asset: image8.png — 1,135 bytes.",
          "Embedded source asset: image9.jpeg — 75,466 bytes."
        ],
        "choices": [
          {
            "label": "Return to the adventure library",
            "target": "__LIBRARY__"
          },
          {
            "label": "Return to the aftermath",
            "target": "aftermath"
          }
        ]
      }
    }
  }
];
